TWEAK_NAME = BatteryBuddy
BatteryBuddy_FILES = BatteryBuddy.m
BatteryBuddy_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
BatteryBuddy_FRAMEWORKS = UIKit
BatteryBuddy_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
