BUNDLE_NAME = BatteryBuddyPreferences
BatteryBuddyPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
BatteryBuddyPreferences_FRAMEWORKS = UIKit
BatteryBuddyPreferences_PRIVATE_FRAMEWORKS = Preferences
BatteryBuddyPreferences_INSTALL_PATH = /Library/PreferenceBundles
BatteryBuddyPreferences_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
