#!/bin/sh

if [ -d /var/mobile/Documents/dev.traurige/ ]; then
    chown -R mobile:mobile /var/mobile/Documents/dev.traurige/
elif [ -d /var/jb/var/mobile/Documents/dev.traurige/ ]; then
    chown -R mobile:mobile /var/jb/var/mobile/Documents/dev.traurige/
fi
